# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker run -it --rm --name assembler assembler-img
      
      - run: docker build --no-cache -t assembler-img .
