# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

executors:
  exectr:
    docker:
      - image: ubuntu:latest

jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          command: |
            apt-get update -y && apt-get install -y --no-install-recommends  \
            gcc                         \
            g++                         \
            make                        \
            build-essential             \
            cmake   &&                  \
            apt-get autoclean       &&                  \
            apt-get autoremove      &&                  \
            apt-get clean           &&                  \
            rm -rf /var/lib/apt/lists/*
      - run:
          command: mkdir -p build

      - run:
          name: Build
          command: |
            cd build
            cmake ..
            make

workflows:
  version: 1.0
  build-and-test:
    jobs:
      - build
